# SPDX-FileCopyrightText: 2021 Carnegie Mellon University
#
# SPDX-License-Identifier: CC0-1.0

# don't check vendorized code
exclude: "^datumaro/.*$"

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

#  - repo: https://github.com/asottile/pyupgrade
#    rev: v2.19.1
#    hooks:
#      - id: pyupgrade
#        name: Modernize python code
#        args: ["--py3-only"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Reorder python imports with isort

  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        name: Format python code with black
        language_version: python3

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        name: Format python code in documentation

  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Lint python code with flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.12.1
    hooks:
      - id: reuse
