[tool.poetry]
name = "opentpod-tools"
version = "0.1.0"
description = "Command line tools integrating OpenTPOD functionality."
authors = [
    "Jan Harkes <jaharkes@cs.cmu.edu>",
]
license = "Apache-2.0"
repository = "https://github.com/cmusatyalab/opentpod-tools/"

[tool.poetry.dependencies]
python = "^3.6"
ConfigArgParse = "^1.2.3"
datumaro = {git = "https://github.com/openvinotoolkit/datumaro", rev = "v0.1.2", extras = ["tf"]}
requests = "^2.24.0"
tqdm = "^4.50.2"
tensorflow = "~1.15.4"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
pylint = "^2.6.0"
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tpod-download = "opentpod_tools.download:main"
tpod-merge = "opentpod_tools.merge:main"

[tool.poetry.urls]
issues = "https://github.com/cmusatyalab/opentpod-tools/issues"
